[build-system]
build-backend = "scikit_build_core.build"
requires = ["scikit-build-core >=0.4.3", "cmake>=3.26"]

[project]
name = "pymagsac"
version = "0.3.dev0"
description = "MAGSAC and MAGSAC++"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Daniel Barath", email = "barath.daniel@sztaki.hu" },
]
dependencies = [
  "numpy"
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3"
]

[project.optional-dependencies]
tests = ["pytest", "opencv-python"]

[tool.pytest.ini_options]
testpaths = 'tests'

[tool.cibuildwheel]
archs = ["auto64"]  # 64-bit only
build = "cp310-* cp311-* cp312-* cp313-* cp314-*"
skip = ["pp*", "*musllinux*"]  # disable PyPy and musl-based wheels
manylinux-x86_64-image = "ghcr.io/akaszynski/manylinux2014-centos7-opencv/manylinux2014_x86_64_opencv3:v3.4.5.4"
test-extras = ["tests"]
test-command = "pytest {project}/tests"

[tool.cibuildwheel.windows]
# Use delvewheel on windows
before-build = "pip install delvewheel abi3audit"

[tool.scikit-build]
wheel.py-api = "cp312"
cmake.args = [
  "-DCMAKE_BUILD_TYPE=Release",
  "-DCREATE_SAMPLE_PROJECT=OFF"
]

# manually specify the following, replacing path with the location of opencv
# CIBW_ENVIRONMENT_WINDOWS "OpenCV_DIR='<PATH>/opencv'"
# CIBW_REPAIR_WHEEL_COMMAND_WINDOWS "delvewheel repair -w {dest_dir} {wheel} --add-path <PATH>/opencv/build/bin"
